### ISSUE TITLE
New Version throws IndexError

### ISSUE THREAD

**Issue by Bush-cat** [PerlinWarp/pygloves-utils#7]
I'm getting an IndexError with the latest release of pygloves, the old version is working. https://github.com/PerlinWarp/pygloves/commit/4851eb73583074a62e376bf2b0c0e9a57f1eb63e
I tried many python version, 3.8 to 3.10, official to winpython to embedded python but couldn't resolve this error
```
Fingers [0, 0, 0, 0, 0]
Listening on COM3
Fingers [0, 0, 0, 0, 0]
Fingers [0, 0, 0, 0, 0]
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Bushcat\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Bushcat\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "B:\Projects\LucidVR\pygloves\lerp_finger_from_serial.py", line 43, in serial_worker
    fingers = s.decode_alpha_serial(read)
  File "B:\Projects\LucidVR\pygloves\serial_utils\serial_read.py", line 29, in decode_alpha_serial
    fingers = [x[1], x[3], x[5], x[7], x[9]]
IndexError: list index out of range
Fingers [0, 0, 0, 0, 0]
Fingers [0, 0, 0, 0, 0]
```

**Comment by Bush-cat** [comment]
using latest lucidgloves firmware on an esp32
https://github.com/LucidVR/lucidgloves/commit/75c0fc13f6c85fa72b577a7440a905da0917c357
